### ISSUE TITLE
HomeBrew package

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-xeus/xeus-cling#151]
It seems that cling has been packaged for brew, hence it should not be too hard to package xeus-cling for that package manager.

**Comment by madhavajay** [comment]
+1 This would be awesome. :)

**Comment by jaens** [comment]
Just curious: What's wrong with Conda?

**Comment by madhavajay** [comment]
miniconda installs a bunch of python and crap I don't want in my system.
I manage my python and its packages independently. Now I have another bin dir in my path which is suppressed to prevent it taking over during other situations.

I know that conda isnt "just python", but look at this dependency graph for the install instructions.

This is the manifest for:
```
$ conda install xeus-cling notebook -c QuantStack -c conda-forge
```

The following NEW packages will be INSTALLED:

    appnope:          0.1.0-py36_0      conda-forge
    backcall:         0.1.0-py_0        conda-forge
    bleach:           2.1.3-py_0        conda-forge
    clangdev:         5.0.0-cling_1     QuantStack  [cling]
    cling:            0.5-2             QuantStack  [cling]
    cling-patches:    1-0               QuantStack
    cppzmq:           4.2.3-cling_0     QuantStack  [cling]
    cryptopp:         5.6.5-cling_0     QuantStack  [cling]
    decorator:        4.3.0-py_0        conda-forge
    entrypoints:      0.2.3-py36_1      conda-forge
    html5lib:         1.0.1-py_0        conda-forge
    icu:              58.2-0            conda-forge
    ipykernel:        4.8.2-py36_0      conda-forge
    ipython:          6.3.1-py36_0      conda-forge
    ipython_genutils: 0.2.0-py36_0      conda-forge
    jedi:             0.12.0-py36_0     conda-forge
    jinja2:           2.10-py36_0       conda-forge
    jsonschema:       2.6.0-py36_1      conda-forge
    jupyter_client:   5.2.3-py36_0      conda-forge
    jupyter_core:     4.4.0-py_0        conda-forge
    libiconv:         1.15-0            conda-forge
    libsodium:        1.0.16-0          conda-forge
    libxml2:          2.9.8-0           conda-forge
    llvmdev:          5.0.0-cling_1     QuantStack  [cling]
    markupsafe:       1.0-py36_0        conda-forge
    mistune:          0.8.3-py36_1      conda-forge
    nbconvert:        5.3.1-py_1        conda-forge
    nbformat:         4.4.0-py36_0      conda-forge
    notebook:         5.4.1-py36_0      conda-forge
    pandoc:           2.1.3-0           conda-forge
    pandocfilters:    1.4.2-py36_0      conda-forge
    parso:            0.2.0-py_0        conda-forge
    pexpect:          4.5.0-py36_0      conda-forge
    pickleshare:      0.7.4-py36_0      conda-forge
    prompt_toolkit:   1.0.15-py36_0     conda-forge
    ptyprocess:       0.5.2-py36_0      conda-forge
    pygments:         2.2.0-py36_0      conda-forge
    python-dateutil:  2.7.2-py_0        conda-forge
    pyzmq:            17.0.0-cling_0    QuantStack  [cling]
    send2trash:       1.5.0-py_0        conda-forge
    simplegeneric:    0.8.1-py36_0      conda-forge
    terminado:        0.8.1-py36_0      conda-forge
    testpath:         0.3.1-py36_0      conda-forge
    tornado:          5.0.2-py36_0      conda-forge
    traitlets:        4.3.2-py36_0      conda-forge
    wcwidth:          0.1.7-py36_0      conda-forge
    webencodings:     0.5.1-py36_0      conda-forge
    xeus:             0.12.0-cling_0    QuantStack  [cling]
    xeus-cling:       0.4.2-0           QuantStack
    xtl:              0.4.7-0           QuantStack
    zeromq:           4.2.3-cling_3     QuantStack  [cling]

The following packages will be UPDATED:

    ca-certificates:  2018.03.07-0                  --> 2018.4.16-0      conda-forge
    certifi:          2018.4.16-py36_0              --> 2018.4.16-py36_0 conda-forge
    conda:            4.5.1-py36_0                  --> 4.5.1-py36_0     conda-forge
    openssl:          1.0.2o-h26aff7b_0             --> 1.0.2o-0         conda-forge

I can install cling with brew. If I can get xeus-cling and a few small dependencies which are probably already in my system from Brew, I can create a jupyter notebook in a virtualenv and symlink it to the C++ kernels. That seems more sane than introducing a whole new package manager and all its crud.

**Comment by SylvainCorlay** [comment]
We are +1 on having xeus and friends packaged for other package managers than conda (brew, apt-get etc...)

**Comment by madhavajay** [comment]
I would love to contribute this if i get some spare time, from what I understand brew recipes arent too hard. Is there a link to where the Conda package instructions are to show whats involved in the current Conda package?

**Comment by diimdeep** [comment]
I tried but couldn't figure out how to build all dependencies ...  

```ruby
class XeusCling < Formula
  desc "Native cling C++ interpreter"
  homepage "https://github.com/QuantStack/xeus-cling"
  url "https://github.com/QuantStack/xeus-cling.git",
      :tag => "0.4.3"
  revision 1

  depends_on "cmake" => :build
  depends_on "zeromq" => :build
  depends_on "cryptopp" => :build
  depends_on "pugixml" => :build

  resource "xtl" do
    url "https://github.com/QuantStack/xtl.git",
        :tag => "0.4.8"
  end

  resource "cppzmq" do
    url "https://github.com/zeromq/cppzmq/archive/v4.2.3.tar.gz"
    sha256 "3e6b57bf49115f4ae893b1ff7848ead7267013087dc7be1ab27636a97144d373"
  end

  resource "nlohmann_json" do
    url "https://github.com/nlohmann/json/archive/v3.1.2.tar.gz"
    sha256 "e8fffa6cbdb3c15ecdff32eebf958b6c686bc188da8ad5c6489462d16f83ae54"
  end

  resource "xeus" do
    url "https://github.com/QuantStack/xeus.git",
        :tag => "0.12.0"
  end

  resource "cxxopts" do
    url "https://github.com/jarro2783/cxxopts.git",
        :tag => "v1.4.4"
  end

  def install
    # (buildpath/"src").install resource("llvm")
    # (buildpath/"src/tools/cling").install buildpath.children - [buildpath/"src"]
    (buildpath/"cppzmq").install resource("cppzmq")
    # (buildpath/"nlohmann_json").install resource("nlohmann_json")
    # (buildpath/"xtl").install resource("xtl")
    (buildpath/"xeus").install resource("xeus")
    (buildpath/"cxxopts").install resource("cxxopts")

    resource("xtl").stage do
      system "cmake", ".", *std_cmake_args
      system "make", "install"
    end

    resource("nlohmann_json").stage do
      system "cmake", ".", *std_cmake_args
      system "make", "install"
    end

    resource("xeus").stage do
      system "cmake", ".", "-Dxtl_DIR=#{lib}/cmake/xtl", 
                           "-Dxtl_DIR=#{lib}/cmake/nlohmann_json",
                            # "-Dnlohmann_json_INCLUDE_PATH=#{buildpath}/nlohmann_json", 
                            *std_cmake_args
      system "make", "install"
    end

    mkdir "build" do
      system "cmake", "-DZMQ_INCLUDE_PATH=#{buildpath}/cppzmq", 
                      "-Dxtl_DIR=#{lib}/cmake/xtl",
                      # "-Dxtl_INCLUDE_PATH=#{buildpath}/xtl", 
                      "-Dxtl_DIR=#{lib}/cmake/nlohmann_json",
                      # "-Dnlohmann_json_INCLUDE_PATH=#{buildpath}/nlohmann_json", 
                      "-Dxeus_INCLUDE_PATH=#{buildpath}/xeus", 
                      "-Dcxxopts_INCLUDE_PATH=#{buildpath}/cxxopts", 
                      *std_cmake_args, "-DCMAKE_INSTALL_PREFIX=#{libexec}", ".."
      system "make", "install"
    end
    # bin.install_symlink libexec/"bin/cling"
    # prefix.install_metafiles buildpath/"src/tools/cling"
  end

  # test do
  #   test = <<~EOS
  #     '#include <stdio.h>' 'printf("Hello!")'
  #   EOS
  #   assert_equal "Hello!(int) 6", shell_output("#{bin}/cling #{test}").chomp
  # end
end
```

**Comment by andrewssobral** [comment]
hello all, some news on this thread?
it would be great to use xeus-cling without conda only using brew

**Comment by robsalasco** [comment]
I'll be happy to use xeus-cling with homebrew! pleaseeee!

**Comment by HWiese1980** [comment]
What's the status here? It's been almost 2 years now and still no `xeus-cling` on HomeBrew?

**Comment by SylvainCorlay** [comment]
Closing the issue as we won't address the homebrew packaging.

**Comment by HWiese1980** [comment]
A pity... are there ways of installing it other than conda? Due to license restrictions I'm not allowed to use conda at my working place. That completely blocks me from using xeus-cling.

**Comment by SylvainCorlay** [comment]
> A pity... are there ways of installing it other than conda?

We only maintain the conda/mamba packages on conda-forge and don't have bandwidth to address other package managers, however others are free to do so.

**Comment by HWiese1980** [comment]
I see. Guess that's a valid excuse ;-) Thanks anyway!

**Comment by qlibp** [comment]
When I install cling with brew, cling works well. However, with conda/mamba installation, cling crash.
Seems that using xeus-cling with brew-installed cling is a better way...
Could anyone show me the way to use brew-installed cling with xeus-cling?
