### ISSUE TITLE
Using miniconda3 to install xeus-cling and importing kernel into another jupyter installation via the kernel spec

### ISSUE THREAD

**Issue by Winterflower** [jupyter-xeus/xeus-cling#246]
> So, the Jupyter notebook server happens to be written in Python, but it is mostly an implementation detail. The fact that it comes with a kernel installed as a package in the same python interpreter is more of a convenience.
> 
> Jupyter can launch kernels for any language, or even other Python installations in your system. For example, you can have a Jupyter installation at the system level (i.e. in Python 2 or 3.x), and a Python 3.6 kernel installed elsewhere in your system (i.e. a conda installation). All you need for the jupyter installation to be aware of the kernels available.
> 
> You can make Jupyter aware of a kernel by installing a `kernel spec` json file with the command
> 
> `jupyter kernelspec install /path/to/kernel/spec/file`.
> 
> This kernel spec contains the information require for Jupyter to be able to launch the kernel, i.e. the executable that implements the communication protocol.
> 
> The C++ kernel is not at all implemented in Python, and is not a Python package. It has really large dependencies like LLVM or Clang.
> 
> ***
> What you can do, is install a miniconda, and the xeus-cling package in that miniconda installation. Refuse to change the `PATH` variable so that the Python that comes with miniconda (as a dependency of conda itself) is not your default Python.
> 
> Then you install the kernel spec in your main  jupyter installation
> ***
> 

_Originally posted by @SylvainCorlay in https://github.com/QuantStack/xeus-cling/issues/80#issuecomment-350225747_

Hi team!
Hope you are well!
I'm trying to install the `xeus-cling` kernel by using the approach suggested by @SylvainCorlay above. I installed miniconda3,  but had to avoid modifying the PATh variable to preserve the integrity of my previous setup. I then created a virtual conda environment and tried to activate it, but was greeted with the error message saying the shell I was using (bash on Mac) was not compatible.
I was able to anyway run `conda install xeus-cling -c conda-forge`, but now I am unable to find the kernel spec. I tried grepping for `kernel.json` inside of the miniconda3 folder that came with the installation and got these results

```
Binary file ./bin/xcpp matches
./conda-meta/xeus-cling-0.6.0-h2dec4b4_0.json:    "share/jupyter/kernels/xcpp11/kernel.json",
./conda-meta/xeus-cling-0.6.0-h2dec4b4_0.json:    "share/jupyter/kernels/xcpp14/kernel.json",
./conda-meta/xeus-cling-0.6.0-h2dec4b4_0.json:    "share/jupyter/kernels/xcpp17/kernel.json",
./conda-meta/xeus-cling-0.6.0-h2dec4b4_0.json:        "_path": "share/jupyter/kernels/xcpp11/kernel.json",
./conda-meta/xeus-cling-0.6.0-h2dec4b4_0.json:        "_path": "share/jupyter/kernels/xcpp14/kernel.json",
./conda-meta/xeus-cling-0.6.0-h2dec4b4_0.json:        "_path": "share/jupyter/kernels/xcpp17/kernel.json",
Binary file ./pkgs/xeus-cling-0.6.0-h2dec4b4_0/bin/xcpp matches
./pkgs/xeus-cling-0.6.0-h2dec4b4_0/info/paths.json:      "_path": "share/jupyter/kernels/xcpp11/kernel.json",
./pkgs/xeus-cling-0.6.0-h2dec4b4_0/info/paths.json:      "_path": "share/jupyter/kernels/xcpp14/kernel.json",
./pkgs/xeus-cling-0.6.0-h2dec4b4_0/info/paths.json:      "_path": "share/jupyter/kernels/xcpp17/kernel.json",
./pkgs/xeus-cling-0.6.0-h2dec4b4_0/info/files:share/jupyter/kernels/xcpp11/kernel.json
./pkgs/xeus-cling-0.6.0-h2dec4b4_0/info/files:share/jupyter/kernels/xcpp14/kernel.json
./pkgs/xeus-cling-0.6.0-h2dec4b4_0/info/files:share/jupyter/kernels/xcpp17/kernel.json
./pkgs/xeus-cling-0.6.0-h2dec4b4_0/info/has_prefix:/opt/anaconda1anaconda2anaconda3 text share/jupyter/kernels/xcpp11/kernel.json
./pkgs/xeus-cling-0.6.0-h2dec4b4_0/info/has_prefix:/opt/anaconda1anaconda2anaconda3 text share/jupyter/kernels/xcpp14/kernel.json
./pkgs/xeus-cling-0.6.0-h2dec4b4_0/info/has_prefix:/opt/anaconda1anaconda2anaconda3 text share/jupyter/kernels/xcpp17/kernel.json
```

Is there a way for me to get the kernel spec file?
Many thanks in advance!

**Comment by JohanMabille** [comment]
Hi,

The package xeus-cling 0.6.0 from conda-forge is broken, we will rebuild it soon. Can you try with xeus-cling 0.5.0 ?

**Comment by zhqu1148980644** [comment]
@Winterflower  Hi, I encountered the same problem, solve by first installing jupyter:
```
conda install xeus-cling notebook -c QuantStack -c conda-forge
```
then the json file:
```
CONDA_PATH/envs/cling/share/jupyter/kernels/xcpp17'
```

**Comment by SylvainCorlay** [comment]
The installation of th kernelspec across environment is documented here: https://xeus-cling.readthedocs.io/en/latest/installation.html#installing-the-kernel-spec.

Closing!
