### ISSUE TITLE
fatal error: 'Python.h' file not found

### ISSUE THREAD

**Issue by pavelschon** [jupyter-xeus/xeus-cling#271]
Using Jupyter+Cling and trying to build simple python extension:
```c++
In [1]: #include <Python.h>

        input_line_8:1:10: fatal error: 'Python.h' file not found
        #include <Python.h>
                 ^~~~~~~~~~
```

Workaround is to add the following lines to `.bashrc`:
```shell
export C_INCLUDE_PATH="~/miniconda3/include/python3.7m/"
export CPLUS_INCLUDE_PATH="~/miniconda3/include/python3.7m/"
```
However, I feel that this should work out-of-the-box without workaround.

This issue is created from https://github.com/ContinuumIO/anaconda-issues/issues/11430 since it's clearly not problem of Anaconda/Miniconda.

**Comment by cauachagas** [comment]
Another solution:

```c++
#pragma cling add_include_path("$CONDA_PREFIX/include/python3.7m/")
#include <Python.h>
```

![image](https://user-images.githubusercontent.com/26585248/72467022-d9742880-37b8-11ea-8a12-1fa0e0b31acb.png)

**Comment by pavelschon** [comment]
Workarounds possible, so closing.
