### ISSUE TITLE
Loading/Using a dynamic library in a Xeus-cling notebook

### ISSUE THREAD

**Issue by engangs** [jupyter-xeus/xeus-cling#299]
Hi all,

I wasn’t able to find a more suitable forum/topic to discuss my problem. Please re-direct if this isn’t the right place to do so.

I am trying to use a C++ framework for a course (do demonstrations & display code stubs & print charts), and chose Xeus-Cling as it integrates well into the Jupyter environment. I am trying to understand how dynamic libraries are loaded and used within the environment, but I am getting errors that I don’t know how to resolve. I started with this code stub that implements a trivial square root function.

```cpp
//mylib.h
#ifndef MYLIB_H
#define MYLIB_H
double calcSqrt(double);
#endif

//calc.c
#include <math.h>
#include "mylib.h"
double calcSqrt(double d)
{
return sqrt(d);
}

#include <stdio.h>
#include "mylib.h"

//main.c
int main()
{
double d = 100;
printf(“sqrt(%3.0f)=%2.0f\n”,d,calcSqrt(d));
return 0;
}
```

I was able to compile the ‘calc.c’ as a dynamic library, and load it with main to get the result. The commands below did not receive any error.

```bash
gcc -c calc.c
gcc -c main.c
gcc -shared -fPIC -o libcalc.so calc.o
gcc main.o ./libcalc.so -lm
./a.out
```

However, when I ported it over to the Jupyter environment, I got an error. This is my code block in Jupyter.

```cpp
#pragma cling add_library_path("<path_of_project>")
#pragma cling load("libcalc")

#include “mylib.h”

calcSqrt(100)
```

This is the error I got. I can’t figure out why since an objdump indicates that function is in the library (.so) file.

```bash
IncrementalExecutor::executeFunction: symbol ‘_Z8calcSqrtd’ unresolved while linking [cling interface function]! You are probably missing the definition of calcSqrt(double) Maybe you need to load the corresponding shared library?

Interpreter Error:
```

Any help will be greatly appreciated. Thanks in advance!

Ed

**Comment by agoose77** [comment]
This is very weak advice but try splitting the pragma directives into different cells (one for each). Restart the kernel and report back your results?

**Comment by JohanMabille** [comment]
If the solution from @agoose77 does not fix your issue, once you have the error, can you execute the following:

```bash
lsof -p <pid>
```

Where `pid` is the id of `xeus-cling` ? (`ps -ef |grep xeus-cling` to get its pid)

**Comment by engangs** [comment]
Hey both, thanks for getting back. I separated them into different cells, restarted and ran the kernel. No joy unfortunately.  

I then ran the lsof command (lsof -p 504), but nothing is returned. Please note that I am running this in Jupyterlab, within a docker container, installed with Ubuntu 18.04.

**Comment by JohanMabille** [comment]
Which compiler did you use to build your library?

**Comment by engangs** [comment]
I installed the binaries using Conda.

**Comment by engangs** [comment]
If you meant my own simple example, I used gcc. Should I be using g++ instead or something else? Thanks Johan.

**Comment by JohanMabille** [comment]
My question was unclear, I wanted to know which compiler and which version of this compiler you used to build libcalc. Also yes I think it could be worth trying with g++

**Comment by engangs** [comment]
Hi Johan,

/# gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by engangs** [comment]
Both, should I use any special switches in my compile settings? Thanks.

**Comment by JohanMabille** [comment]
No, it should work out of the box. I just tried your example locally and had no issue :/

Can you print the result of the following:

```bash
ld --version
conda list | grep binutils
```

**Comment by engangs** [comment]
Hi Johan,

/# ld --version
GNU ld (GNU Binutils for Ubuntu) 2.30
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

/# conda list | grep binutils
binutils_impl_linux-64    2.33.1               h53a641e_8    conda-forge
binutils_linux-64         2.33.1              h9595d00_16    conda-forge

**Comment by engangs** [comment]
Did you use g++ or gcc to compile? Thanks.

**Comment by JohanMabille** [comment]
I built with g++. I have exactly the same versions of binutils, so the problem does not come from it.

**Comment by engangs** [comment]
Hi Johan, good news. I recompiled with g++ and it worked. I thought that g++ as a compiler is a superset of gcc, like the language. Looks like that is wrong.

**Comment by JohanMabille** [comment]
Nice!
