### ISSUE TITLE
install xeus-cling using pip?

### ISSUE THREAD

**Issue by Dishendramishra** [jupyter-xeus/xeus-cling#301]
I want to install **xeus-cling**, but I want to install it without anaconda. can I install it using pip or any other way?

**Comment by JohanMabille** [comment]
This is a pure C++ program, so installing it from pip does not really make sense. The only alternative is to build it from sources, but you need to get the dependencies somehow.

What prevents you from using conda?

**Comment by martinRenou** [comment]
Just a note on the fact you can use miniconda, this is smaller than installing anaconda. https://docs.conda.io/en/latest/miniconda.html

**Comment by pojntfx** [comment]
I've set up CI-built binary packages for xeus-cling which can be installed without conda (or the other dependencies): https://github.com/jupyter-xeus/xeus-cling/issues/327#issuecomment-787071745
