### ISSUE TITLE
Add jupyter to conda installation or update README

### ISSUE THREAD

**Issue by jgbradley1** [jupyter-xeus/xeus-cling#305]
I'm using miniconda 3 (conda 4.8.2) on Ubuntu 18.04. After following the installation instructions
```
conda create -n cling
conda activate cling
conda install xeus-cling -c conda-forge
```
I was surprised to find that Jupyter does not get installed as a dependency. This seems to make it extra difficult to get started. The README directions state to run `jupyter notebook` to launch and get started, yet gloss over installing jupyter . I found a solution [here](https://github.com/jupyter-xeus/xeus-cling/issues/246) which appears to work.

```
conda install xeus-cling notebook -c QuantStack -c conda-forge
```

Can Jupyter be added as a dependency or the README instructions be updated to reflect the installation of jupyter?

**Comment by JohanMabille** [comment]
Strictly speaking it is not a dependency, any frontend that implement the Jupyter protocol can interact with xeus-cling.

However I agree with you that the README instructions could be updated so beginners can just follow them and have something working.
