### ISSUE TITLE
Button with callback

### ISSUE THREAD

**Issue by engangs** [jupyter-xeus/xeus-cling#306]
Hi,

I am trying to implement a button widget, which will trigger a callback function. I had a look at xwidgets but the example (https://xwidgets.readthedocs.io/en/latest/usage.html) does not work.

xw::button button;

void foo()
{
    std::cout << "Clicked!" << std::endl;
}

button.on_click(foo);
button.display(); 

I am thinking of using rich text display to display a html based button, and somehow embed a callback, which is triggered by an on-click event. However, I need some guidance on how I should do so. Specifically, the example below, provided in the xeus example, will be a good start. Advice on how to hack this to make it work will be appreciated, thanks.

#include <string>
#include "xcpp/xdisplay.hpp"

#include "nlohmann/json.hpp"

namespace nl = nlohmann;

namespace ht
{
    struct html
    {   
        inline html(const std::string& content)
        {
            m_content = content;
        }
        std::string m_content;
    };

    nl::json mime_bundle_repr(const html& a)
    {
        auto bundle = nl::json::object();
        bundle["text/html"] = a.m_content;
        return bundle;
    }
}

// A blue rectangle
ht::html rect(R"(
<div style='
    width: 90px;
    height: 50px;
    line-height: 50px;
    background-color: blue;
    color: white;
    text-align: center;'>
Original
</div>)");

**Comment by martinRenou** [comment]
Are you using JupyterLab or the classic Jupyter Notebook? It behaves differently with `std::cout` calls in callback functions. JupyterLab does not display it. But you can try capturing the output with an `xoutput` widget.

**Comment by engangs** [comment]
Hi Martin,

Thanks for getting back. I am getting this error message.

**Comment by martinRenou** [comment]
cling can be pretty annoying with function definitions... Try defining your `foo` function in a specific cell. And define you button in another cell.

**Comment by engangs** [comment]
Hi, I got the same error, when they are separated in different cells. Ed

**Comment by martinRenou** [comment]
Do you mind sharing a screenshot of your notebook? So we can have see the entire code at once, see what's missing

**Comment by engangs** [comment]
![error](https://user-images.githubusercontent.com/56570446/76399322-63a3cc00-63b9-11ea-813e-da6430413f2f.png)

**Comment by martinRenou** [comment]
Like I said, put the `foo` function in a specific cell, alone. It should work.

**Comment by engangs** [comment]
Sorry, you are right. There is no error when the function is alone. However, I replaced the function body, and nothing happens when I click the button. Again, advice appreciated, thanks.

![no_action](https://user-images.githubusercontent.com/56570446/76405107-9d2d0500-63c2-11ea-875c-846649034e71.png)

**Comment by engangs** [comment]
Actually, the animation came out in the log messages. Is there anyway of re-directing this to the notebook instead? Thanks.

**Comment by engangs** [comment]
Ok, got it working with xout. Thanks for the tip, Martin.
![button_widget](https://user-images.githubusercontent.com/56570446/76411741-5ee91300-63cd-11ea-9167-b0039ae28038.png)

**Comment by martinRenou** [comment]
Sure!
