### ISSUE TITLE
Problem displaying output in cell

### ISSUE THREAD

**Issue by grassjelly** [jupyter-xeus/xeus-cling#309]
**System Information:**
Operating System: Ubuntu 16.04.6 
Kernel: 4.15.0-88-generic
Architecture: x86_64
Conda Version: 4.7.12
Notebook Kernel: C++11
Packages installed:
- ros-core
- ros-actionlib
- ros-dynamic-reconfigure
- xeus-cling
- pybind11
- jupyter
- ipywidgets
- jupyros

**Problem:**
I'm trying to write a wrapper for [jupyter-ros](https://github.com/RoboStack/jupyter-ros) using [pybind11](https://anaconda.org/conda-forge/pybind11) to call the python libraries in c++.

I managed to run the ported codes in my notebook successfully but I can't seem to display the output in the next cell. The kernel just restarts displaying this message every time I call v.

> The kernel appears to have died. It will restart automatically.

Here's the Python jupyter-ros code:
```
from jupyros import ros3d
v = ros3d.Viewer()
rc = ros3d.ROSConnection()
tf_client = ros3d.TFClient(ros=rc, fixed_frame="")
v
```

and here's my c++ code trying to replicate the same in c++ using pybind11:
```
#pragma cling add_include_path("/home/juan/miniconda3/envs/test/include/python3.6m")
#pragma cling add_include_path("/home/juan/miniconda3/envs/test/include")
#pragma cling add_library_path("/home/juan/miniconda3/lib")

#pragma cling load("python3.6m")
#include <pybind11/embed.h>
#include <iostream>
#include <xcpp/xdisplay.hpp>

namespace py = pybind11;
using namespace pybind11::literals; 
py::scoped_interpreter python;

auto ros3d = py::module::import("jupyros").attr("ros3d");
auto v = ros3d.attr("Viewer")();
auto rc = ros3d.attr("ROSConnection")();
auto tf_client = ros3d.attr("TFClient")("ros"_a=rc, "fixed_frame"_a="");
v
```
This is the expected output from jupyter-ros:
![jupyterros](https://user-images.githubusercontent.com/5070395/76611473-88cd4180-6555-11ea-8712-d21b03619a87.jpg)

**Comment by martinRenou** [comment]
Interesting approach!

I am a bit confused though. I am not 100% this can work. Do you get an error message when executing this code? ipywidgets depends on ipython for the comms implementation (communication between the Python back-end and the JavaScript front-end), but here you try to use ipywidgets from the C++ kernel, so ipython must be missing.

I am curious to know how it fails though. Do you have ipython installed in your environment?

Another way of doing what you want would be to implement the C++ back-end for `jupyros`, just like xwidgets is the C++ back-end for ipywidgets and xleaflet the C++ back-end for ipyleaflet. But it's definitely more work than what you are trying to achieve with pybind11.

**Comment by grassjelly** [comment]
Thanks for your response. I have ipython installed in my environment. There's no error when I run the cell but the kernel keeps restarting. I think I would have to go with your advice which is to do it natively in the back-end. 

Closing this for now. Thank you!
