### ISSUE TITLE
Can I specify C++20?

### ISSUE THREAD

**Issue by pdeitel** [jupyter-xeus/xeus-cling#326]
Is there somewhere I can pass -std=C++2a to take advantage of new C++20 features that are already implemented?

**Comment by SylvainCorlay** [comment]
Hello @pdeitel this is not possible at the moment as cling is currently based on clang 5 which does not support c++20.

**Comment by pdeitel** [comment]
Any idea when the clang version that the kernel uses might get upgraded?

**Comment by SylvainCorlay** [comment]
This is dependent on the core cling team. I know that they are actively working on it but releases are not frequent.

**Comment by sean-parent** [comment]
Cling 0.9 is clang 9 based which should have some support for `-std=C++2a` - would it be possible to have this added?
