### ISSUE TITLE
Install without Anaconda/Miniconda

### ISSUE THREAD

**Issue by MinerChAI** [jupyter-xeus/xeus-cling#327]
I don't like anaconda because I prefer using existing python instance instead of anaconda one, and anaconda breaks everything

**Comment by JohanMabille** [comment]
> and anaconda breaks everything

My computers run fine with Miniconda.

You can install from sources (but you need to be careful to use the same cxxstd library for the whole chain).

**Comment by SylvainCorlay** [comment]
Also, xeus-cling and anaconda have nothing to do with Python.

**Comment by MinerChAI** [comment]
> Also, xeus-cling and conda have nothing to do with Python.

Conda does?

**Comment by SylvainCorlay** [comment]
> Conda does?

It is written *in*  python, but it is a general-purpose package manager. In fact, we are working on a C++ client to conda packages...

**Comment by MinerChAI** [comment]
But it does change default python interpreter

**Comment by SylvainCorlay** [comment]
Only if you forcibly make it do so.

**Comment by pojntfx** [comment]
To those looking to install it without Miniconda (didn't want to add a dependency on it to `pojde-ng`), I set up a repo which uses GitHub actions to build portable x86_64/aarch64 binary packages; this allows you to install xeus-cling without dependencies: https://github.com/pojntfx/xeus-cling-binaries
