### ISSUE TITLE
Kernel crashes on pressing TAB

### ISSUE THREAD

**Issue by tbhaxor** [jupyter-xeus/xeus-cling#330]
Steps to reproduce
**CELL1**
```cpp
#include "iostream"
```
**CELL2**
```cpp
std::<TAB><TAB>
```

The kernel crashes after this.

**Comment by SylvainCorlay** [comment]
Thanks @tbhaxor. Closing as a duplicate of https://github.com/jupyter-xeus/xeus-cling/issues/41.
