### ISSUE TITLE
Unable to find Kernel in Jupiter Lab

### ISSUE THREAD

**Issue by ahlag** [jupyter-xeus/xeus-cling#331]
I have installed Jupyter Lab with pip and when I tried installing xeus-cling with conda, I couldn't find the kernel on the notebook. Is there a workaround to move all the dependencies so that the Jupyter Lab I installed using pip knows where to get the dependencies? Many thanks.

**Comment by JohanMabille** [comment]
You need to find the folder where Jupyterlab searches for the kernelspec (usually something like `share/jupyter/kernels`) in your pip virtual env.
Then find the kernelspec of xeus-cling (under a similar folder) in your conda environment and copy it to the previous folder. Copy the folder including a .json and logo files, not only the json flie.

Or simply install Jupyterlab with conda.

**Comment by ahlag** [comment]
Thank you so much @JohanMabille !
