### ISSUE TITLE
xeus-cling and mkl?

### ISSUE THREAD

**Issue by Data-drone** [jupyter-xeus/xeus-cling#337]
Why does Xeus-cling conda package remove mkl?

I was just trying to install xeus-cling using conda as per the instructions but the conda install `4.6.14` says that mkl will be removed as part of this

**Comment by JohanMabille** [comment]
Looks like a conda issue. Installing with conda 4.8.3 does not remove mkl, but replaces it with that from the default channel (which seems to still be an issue, but at least it does not remove the package)

**Comment by SylvainCorlay** [comment]
The conda solver can behave weirdly sometimes.

If this is an issue, you can use mamba instead of conda (to install conda packages). Mamba tends to behave in a more stable way in my experience.

**Comment by SylvainCorlay** [comment]
Closing as unrelated to xeus-cling.
