### ISSUE TITLE
Use a c++ with Jupyter Notebook in windows 

### ISSUE THREAD

**Issue by MuhammadAlBarham** [jupyter-xeus/xeus-cling#342]
Thanks for your effort for creating this for Linux and OS X platforms. But, I need to use a Jupyter notebook with c++ locally. 

How can I do that? 

Is another conda's package for that?

**Comment by rangerscience** [comment]
My workaround it to use Docker on Windows. And/or the Windows Linux Subsystem.

**Comment by MuhammadAlBarham** [comment]
Thank you, I will check it.
