### ISSUE TITLE
jupyter notebook xeus cling not including 3rd party libraries

### ISSUE THREAD

**Issue by offset-null1** [jupyter-xeus/xeus-cling#356]
- System: Ubuntu 18.04 LTS
- Env: conda
- Kernel: xeus cling cpp-11

I want to use PyTorch c++ in jupyter cling. However, I'm struggling to include header files.

```
#pragma cling load("/libtorch/lib/libc10.so")
#pragma cling load("/libtorch/lib/libgomp-4f651535.so.1")
#pragma cling load("/libtorch/lib/libtorch.so")
#include<torch/torch.h>

```
I have copied /torch and /csrc to /usr/lib directory but it's showing the following error:

> input_line_12:1:9: fatal error: 'torch/torch.h' file not found
> #include<torch/torch.h>
>         ^~~~~~~~~~~~~~~

**Comment by cauachagas** [comment]
It's missing `add_include_path`

```c++
#pragma cling add_include_path("/path/to/libtorch/include")
#pragma cling add_include_path("/path/to/libtorch/include/torch/csrc/api/include")
```

**Comment by offset-null1** [comment]
I modified as you said, but it's still giving me the same error. What could be wrong?

**Comment by offset-null1** [comment]
Thanks!
