### ISSUE TITLE
std::cout not working

### ISSUE THREAD

**Issue by offset-null1** [jupyter-xeus/xeus-cling#359]
Hi, I'm using c++11 kernel in jupyter notebook.

`#include<iostream>`

```
int main(){
    std::cout<<"Hey"<<"\n";
    return 0;
}
```
It's not printing out the output. Can someone please tell me how would I resolve this?

**Comment by martinRenou** [comment]
You don't need to define a `main` function. The main is the Notebook itself. The main function you define here is never called.

**Comment by martinRenou** [comment]
Try putting only this in your cell
```cpp
#include<iostream>

std::cout << "Hey" << "\n";
```

**Comment by offset-null1** [comment]
Thanks.
