### ISSUE TITLE
 Is there any missing feature of pure C (not C++)?

### ISSUE THREAD

**Issue by Naereen** [jupyter-xeus/xeus-cling#386]
Hello there,
First of all, :clap: :clap: this project is amazing, I've using it from time to time since a few months, and I really like it!
 It can be a great tool for teaching I think! So thanks!

Regarding teaching, I'll have to teach a few introduction courses to C (not C++), and of course I'll start by using a local real compiler for C, but I would like to also have such basic interactive environment.
I know Jupyter also has [a C kernel](https://github.com/brendan-rius/jupyter-c-kernel), and this one is the only one I'm aware of... but as it's name says, it's pretty minimal.

I'm not a very strong expert of C and C++, but from what I understood, any valid C99 or C11 program is also valid in C++, with the same semantic, so I can expect `xeus-cling` to be able to run correctly any (small and simple enough) C program?

My question is in the title: Is there any (known) missing feature of pure C (not C++)?

I wasn't able to find the answer on [CLING](https://root.cern/cling/) documentation, so I prefer to ask here.

Thanks!
Regards from France, @Naereen

**Comment by Naereen** [comment]
I link here a similar question I've opened on JSCPP, a pure javascript interpreter for C++ that I also intend to use for my teaching. https://github.com/felixhao28/JSCPP/issues/146

**Comment by JohanMabille** [comment]
Hi,

I've never tried to use pure C with `xeus-cling`, but `xeus-cling` relies on `cling` which in turn relies on `clang` and `llvm`. So I guess it should work out of the box, and any missing / non working feature could be reported as a bug.

**Comment by Naereen** [comment]
Great, thanks for the answer @JohanMabille !

**Comment by Naereen** [comment]
Hi Sylvain,
Thanks for the answer.
Yes the C kernel is quite limited as it just compiles & runs the code for you, so it can be great to teach about compiling C to native code.

I'll keep learning C and what C features are not supported by Clang (hence by Cling hence by this kernel), but my guess is that I can safely assume any reasonable "L1/L2 Bachelor" programs in C will work perfectly using the C++ kernel. (I'll have to teach that at CPGE level soon!)

Thanks! @Naereen
