### ISSUE TITLE
I am getting a package not found error 

### ISSUE THREAD

**Issue by MFRSiam** [jupyter-xeus/xeus-cling#414]
![Screenshot 2021-08-11 173541](https://user-images.githubusercontent.com/12758535/129910378-d6af7d5d-201a-4b18-8953-a2b570e3849c.png)

**Comment by SylvainCorlay** [comment]
Indeed, xeus-cling is not available for windows on conda-forge!

**Comment by mulderp** [comment]
indeed, I am able to run Xeus-Cling with help of WSL some links to make it easier to get started:
* Install WSL
* Curl install miniconda/mamba
* https://xeus-cling.readthedocs.io/en/latest/installation.html# 
* run jupyter on WSL with this option enabled https://stackoverflow.com/questions/62814002/start-this-command-cannot-be-run-due-to-the-error-the-system-cannot-find-the
