### ISSUE TITLE
can not install on jupyter-hub "ResolvePackageNotFound:    - conda==4.10.3"

### ISSUE THREAD

**Issue by azataiot** [jupyter-xeus/xeus-cling#437]
```
jupyter-azat@vmi798119:~$ sudo -E conda install xeus-cling -c gouarin -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

ResolvePackageNotFound: 
  - conda==4.10.3
```

**Comment by azataiot** [comment]
OS version: Ubuntu 22.04, 
Jupyter Hub installation: TLJH fresh installation.

**Comment by LuckyBoy314** [comment]
Don't install it in conda base env, create a new virtual env!

`sudo -E create -n cling
# 'sudo -E '   is not needed, you may run 'conda init' before run this command.
conda activate cling        
sudo -E conda install xeus-cling -c conda-forge
jupyter kernelspec install /opt/tljh/user/envs/cling/share/jupyter/kernels/xcpp11 --sys-prefix`

but  C++17 does not work, C++11 and C++14 work properly on my machine(OS version: WSL2 Ubuntu 20.04,Jupyter Hub installation: TLJH fresh installation)
