### ISSUE TITLE
features.h not found

### ISSUE THREAD

**Issue by chavid** [jupyter-xeus/xeus-cling#521]
Hello.
I'm trying again to build a docker recipe for a jupyter lab image with xeus-cling.
I can't get rid of a "features.h not found" error when I run any C++17 notebook.
My latest simplified  recipe attempt below.
Any idea welcome.

```
FROM quay.io/condaforge/miniforge3
RUN mamba install -y jupyterlab
RUN mamba install -y xeus-cling
ENTRYPOINT [ "jupyter", "lab", "--port=8888", "--ip=0.0.0.0", "--no-browser","--allow-root"]
```

**Comment by nthiery** [comment]
Just as a data point: this (big) environment worked smoothly last time I installed it (about one month ago):

https://gitlab.dsi.universite-paris-saclay.fr/Info111/ComputerLab/-/blob/master/binder/environment.yml

The difference could be in:
- cxx-compiler
- compiler-rt 

It would be preferable indeed if the simplified recipe above worked at once.

**Comment by chavid** [comment]
Which docker image you started from ?
I have the same symptoms with either quay.io/condaforge/mambaforge or continuumio/miniconda3, whatever the version.
The difference is maybe in the fact to install within a dedicated environment or not.

**Comment by chavid** [comment]
After dozens of failures, I got it to work starting from a fresh miniconda python311 installation. That was a fight, especially because I was also needing the classical notebooks and old-style rise activated (I dislike default code extracts font sizes with the new jupyterlab_rise).

**Comment by nthiery** [comment]
In docker: mambaorg/micromamba:latest. Also on my machine with a mambaforge install.

Have you tried jupyterlab-deck? I find it more robust and less interfering with JupyterLab's
user interface (style, ...). Just don't use subslides for now. (sorry for derailing in this thread).

https://jupyterlab-deck.readthedocs.io/
