### ISSUE TITLE
A quote in a comment makes the cell inactive

### ISSUE THREAD

**Issue by nthiery** [jupyter-xeus/xeus-cling#64]
If a comment contains a quote, then evaluating the cell does nothing:

![test-quote-in-comment](https://user-images.githubusercontent.com/545328/31044768-adcc526a-a5d5-11e7-9e87-a01628cdcb45.png)

**Comment by SylvainCorlay** [comment]
This seems to be an issue with upstream cling.

**Comment by nthiery** [comment]
For the record: this has evolved slightly: now evaluating the cell triggers an InterpreterError. Has it been reported upstream? I tried reproducing it with cling but I am not sure this is very useful:
```
[cling]$ /* ' */
[cling]$ ?   
```

**Comment by nthiery** [comment]
```
$ conda list | grep cling
clangdev                  5.0.0                   cling_1  [cling]  QuantStack
cling                     0.5                           7  [cling]  QuantStack
cling-patches             1                             0    conda-forge
cryptopp                  5.6.5                   cling_0  [cling]  QuantStack
llvmdev                   5.0.0                   cling_1  [cling]  QuantStack
pyzmq                     17.0.0                  cling_0  [cling]  QuantStack
xeus                      0.14.1                  cling_0  [cling]  QuantStack
xeus-cling                0.4.7                         0    QuantStack
zeromq                    4.2.5                   cling_0  [cling]  QuantStack
```

**Comment by nthiery** [comment]
For the record: this is still failing with conda 0.7 and xeus-cling 0.10.0.

**Comment by nthiery** [comment]
For the record: the example above now works smoothly with cling 0.8 and xeus-cling 0.13.0.
```
/* ' */
1 + 1
```
I tried a few other examples without failure. So I am assuming that this is fixed and the issue can be closed.
