### ISSUE TITLE
Implement the analog of IPython's %time

### ISSUE THREAD

**Issue by nthiery** [jupyter-xeus/xeus-cling#65]
Just dreaming aloud :-)

**Comment by gouarin** [comment]
The timeit magic function is implemented

See

%timeit for single line

Or

%%timeit for a cell


Le 30 sept. 2017 11:56 AM, "Nicolas M. Thiéry" <notifications@github.com> a
écrit :

**Comment by nthiery** [comment]
Ça c'est de la réponse rapide, surtout pour un samedi matin :-)

Would you have an example? I did not manage to make it work (xeus 0.6.0, xeus-cling 0.0.5). I tried the obvious:
```
%timeit 1+1
%timeit "1+1"
```
and variants with a function call for something less trivial and %%timeit for cell-wide.

**Comment by gouarin** [comment]
You forget to add a semicolon add the end of the line.

**Comment by nthiery** [comment]
Ah yes, I should have mentionned I was getting the following error with the semicolon:
```
%timeit 1+1;
In file included from input_line_3:1:
/opt/miniconda3/gcc/include/c++/chrono:199:58: error: no type named 'type' in 'std::common_type<double, long, long>'
        typedef typename common_type<__to_rep, _Rep, intmax_t>::type
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/opt/miniconda3/gcc/include/c++/chrono:271:10: note: in instantiation of function template specialization 'std::chrono::duration_cast<std::chrono::duration<double, std::ratio<1, 1> >, long, std::ratio<1, 1000000000> >' requested here
          : __r(duration_cast<duration>(__d).count()) { }
                ^
input_line_59:7:1: note: in instantiation of function template specialization 'std::chrono::duration<double, std::ratio<1, 1> >::duration<long, std::ratio<1, 1000000000>, void>' requested here
std::chrono::duration<double>(_t1-_t0).count();
...
```
Full log: [log.txt](https://github.com/QuantStack/xeus-cling/files/1346339/log.txt)

**Comment by gouarin** [comment]
@SylvainCorlay @JohanMabille do you have the same issue ?

I can't reproduce this one.

I think it is an installation issue of `xeus-cling`. 

@nthiery how do you install `xeus-cling` and on which OS ?

**Comment by nthiery** [comment]
Ah, right, it works well on Orsay's JupyterHub, as well as on the test machine for the SIF teaching labs (recent linux mint, xeus-cling 0.0.5 installed within anaconda3).
So we can try to use it next week in class :-)

I am on a Unbuntu 17.04; xeus-cling was installed a few weeks ago within a pristine miniconda. I upgraded this morning to the latest version which did not fix the issue. Best not waste more time on it, and investigate together on Tuesday.
Thanks!

**Comment by SylvainCorlay** [comment]
We might be interested in having a separation of the compilation and runtime with the `%%time` magic.

**Comment by SylvainCorlay** [comment]
cc @vgvassilev
