### ISSUE TITLE
nb_conda support

### ISSUE THREAD

**Issue by RafalSkolasinski** [jupyter-xeus/xeus-cling#95]
It would be cool if xeus-cling kernel would be detectable via ``nb_conda``.

**Comment by SylvainCorlay** [comment]
Hi @RafalSkolasinski what would it take for `xeus-cling` to be detectable by `nb_conda`?

**Comment by SylvainCorlay** [comment]
Closing as I don't think this is as much of an issue for xeus-cling as for nbconda!

**Comment by benbovy** [comment]
Since v2.2.0 [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels) can detect kernels beyond Python and R, including xeus-cling.

**Comment by SylvainCorlay** [comment]
Great!
